# Copyright 2018 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

baseURL = "https://fission.io/"
enableRobotsTXT = true
title = "Fission"

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
author = "author"
category = "categories"
tag = "tags"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = []

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories", "Authors"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories", "authors"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/posts/:slug/"

[markup.goldmark.renderer]
unsafe = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

# Language configuration

[languages]
[languages.en]
description = "Fast Serverless Functions for Kubernetes"
languageName = "English"
title = "Fission"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "Copyright © 2020 Fission Project"
github_repo = "https://github.com/fission/fission.io"
github_project_repo = "https://github.com/fission/fission"
privacy_policy = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "013477323950444988730:is1ujykktrh"

# current release branch - could be rc
release_branch = "master"
# the main version. Never is rc.
release_version = "1.14.1"

slackurl = "https://join.slack.com/t/fissionio/shared_invite/enQtOTI3NjgyMjE5NzE3LTllODJiODBmYTBiYWUwMWQxZWRhNDhiZDMyN2EyNjAzMTFiYjE2Nzc1NzE0MTU4ZTg2MzVjMDQ1NWY3MGJhZmE"

installurl = '/docs/installation/'
learnmoreurl = '/docs/installation/'
twitterurl = 'https://twitter.com/fissionio'

notoc = true

[params.social]
github = 'fission'
slackurl = "https://join.slack.com/t/fissionio/shared_invite/enQtOTI3NjgyMjE5NzE3LTllODJiODBmYTBiYWUwMWQxZWRhNDhiZDMyN2EyNjAzMTFiYjE2Nzc1NzE0MTU4ZTg2MzVjMDQ1NWY3MGJhZmE"
twitter = 'fissionio'

[[params.whatsnew]]
badge = 'FISSION DZONE REFCARD'
body = 'Get started with Serverless on Kubernetes in 5 minutes! Learn how to set up Fission, its key concepts, how to create and invoke a function, monitor its performance, and more.'
heading = 'New! Download the Fission.io Refcard'
[params.whatsnew.button]
hero_class = 'mid'
text = 'Download Now!'
url = 'https://platform9.com/wp-content/uploads/2019/03/dzone-refcard-fissionio.pdf'

[[params.whatsnew]]
badge = 'BLOG'
body = 'In this post we will look into how we can develop a simple a web socket based chat application using Fission functions.'
heading = 'Fission WebSocket Sample'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'Read More!'
url = 'https://fission.io/posts/websocket-sample/'

[[params.whatsnew]]
badge = 'PODCAST'
body = 'Soam Vasani – the creator of Fission – sat down with Jeffrey Meyerson from Software Engineering Daily podcast to talk all-things serverless and Kubernetes.'
heading = 'Talking Serverless on Kubernetes with Software Engineering Dail'
[params.whatsnew.button]
hero_class = 'mid-2'
text = 'Listen Now!'
url = 'https://platform9.com/blog/talking-serverless-on-kubernetes-with-software-engineering-daily'

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = false
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
no = 'Sorry to hear that. Please <a href="https://github.com/fission/fission/issues/new">tell us how we can improve</a>.'
yes = 'Glad to hear it! Please <a href="https://github.com/fission/fission/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
desc = "Follow us on Twitter to get the latest news!"
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/fissionio"
[[params.links.user]]
desc = "Chat with other project users in #users"
icon = "fab fa-slack"
name = "Slack"
url = "https://join.slack.com/t/fissionio/shared_invite/enQtOTI3NjgyMjE5NzE3LTllODJiODBmYTBiYWUwMWQxZWRhNDhiZDMyN2EyNjAzMTFiYjE2Nzc1NzE0MTU4ZTg2MzVjMDQ1NWY3MGJhZmE"
[[params.links.user]]
desc = "Development takes place here!"
icon = "fab fa-github"
name = "GitHub"
url = "https://github.com/fission/fission"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[menu]
[[menu.main]]
name = "Docs"
url = "/docs/"
pre = "<i class='fas fa-book'></i>"
weight = 10
[[menu.main]]
name = "Blog"
url = "/blog/"
pre = "<i class='fas fa-blog'></i>"
weight = 11
[[menu.main]]
name = "Environments"
pre = "<i class='fas fa-store'></i>"
url = "https://environments.fission.io/"
weight = 12
[[menu.main]]
name = "GitHub"
pre = "<i class='fab fa-github'></i>"
url = "https://github.com/fission"
weight = 13
[[menu.main]]
name = "Slack"
pre = "<i class='fab fa-slack'></i>"
url = "https://join.slack.com/t/fissionio/shared_invite/enQtOTI3NjgyMjE5NzE3LTllODJiODBmYTBiYWUwMWQxZWRhNDhiZDMyN2EyNjAzMTFiYjE2Nzc1NzE0MTU4ZTg2MzVjMDQ1NWY3MGJhZmE"
weight = 14
